server {
    listen 80;
    server_name olderfriends.org www.olderfriends.org;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /2mancheck.hmtl {
        default_type text/html;
    }


    location /api/ftc-rss {
        proxy_pass https://consumer.ftc.gov/blog/gd-rss.xml;
        proxy_set_header Host consumer.ftc.gov;
        proxy_ssl_server_name on;
    }

    location /api/substack-rss {
        proxy_pass https://olderfriends.substack.com/feed;
        proxy_set_header Host olderfriends.substack.com;
        proxy_ssl_server_name on;
    }

    location ~ /ads.txt {
        return 301 https://srv.adstxtmanager.com/19390/olderfriends.org;
    }
}
